version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: "npm run start"
    volumes:
      - .:/usr/src/app/
    ports:
      - "3001:3001"
    environment:
      - AUTH_API_PORT=3001
      - AUTH_API_URL=http://${HOSTNAME}:3001
      - AUTH_WEBSITE_PORT=3000
      - AUTH_WEBSITE_URL=http://${HOSTNAME}:3000
