version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: "npm run start"
    volumes:
      - .:/usr/src/app/
    ports:
      - "3001:3001"
